version: '3.9'
services:
  nginx:
    image: nginx-net:1.18.0
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    ports:
      - 5000:80
    environment:
      TZ: "Europe/Moscow"
    configs:
      - source: nginx-net.conf
        target: /etc/nginx/sites-available/nginx-net.conf
    depends_on:
      - net
  net:
    image: net:1.0
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    environment:
      TZ: "Europe/Moscow"
configs:
  nginx-net.conf:
    file: nginx-net.conf
