version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    image: nginx-net:1.18.0
    container_name: nginx-net
    ports:
      - 80:80
    volumes:
      - ./nginx-net.conf:/etc/nginx/sites-available/nginx-net.conf
    depends_on:
      - net
  net:
    build:
      context: ./
      dockerfile: Dockerfile
    image: net:1.0
    container_name: net
    ports:
      - 4000:80
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1'
